# Generated by Django 4.1.7 on 2023-07-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
    ]
