# Generated by Django 4.1.7 on 2023-07-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncweb', '0005_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.AddField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(related_name='products', to='cncweb.collection'),
        ),
    ]
